# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_group',
            fields=[
                ('GROUP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GROUP_NAME', models.CharField(max_length=64, verbose_name='\u7ec4\u540d')),
            ],
            options={
                'db_table': 'user_group',
                'verbose_name': '\u7ec4\u5217\u8868',
            },
        ),
    ]
