# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_group',
            options={'verbose_name': '\u7528\u6237\u7ec4', 'verbose_name_plural': '\u7528\u6237\u7ec4'},
        ),
        migrations.AlterField(
            model_name='user_group',
            name='GROUP_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u7ec4ID'),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='GROUP_NAME',
            field=models.CharField(max_length=64, verbose_name='\u7528\u6237\u7ec4\u540d'),
        ),
    ]
